version: "3"

services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  hermes:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres:
